### ISSUE TITLE
你好  能释放apk吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [fantasyRqg/TVM_Android_rpc#2]
你好
      最近在学习tvm的模型部署，对这个项目很感兴趣，请问这项目是完整的吗？我看rpc_env.cc  rpc_server.cc 这两个文件没有。
谢谢！

**Comment by fantasyRqg** [comment]
这两个文件是tvm cpp_rpc 的一部分， README 中需要配置的文件就是指向 tvm 源码的。 如果tvm 源码变化不大，直接配置应该就可以编译

**Comment by zuowanbushiwo** [comment]
好的，谢谢！感觉你这个比官网的那个编译要简单些。请问你当时是基于tvm的哪个版本(commit)？我和你搞一样的环境。

**Comment by fantasyRqg** [comment]
no_acl branch 适配了tvm commit  59c0ef80b5186e1840523f6a8b60071f78436212

**Comment by zuowanbushiwo** [comment]
好的，谢谢！
